/tars_dog:
  ros__parameters:
    semantic_map_path: "/home/eatwhat/ws_decision/src/tars_decision/config/rmuc_map.xml"
    color: 0 # 0为蓝方， 1为红方
    red:
      goalNoBullet: # 无子弹点
        x: 4.53
        y: 2.92
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalBasePatrolA: # 基地巡逻点
        x: 4.87
        y: 1.07
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalBasePatrolB: # 基地巡逻点
        x: 8.52
        y: 7.36
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalBasePatrolC: # 基地巡逻点
        x: -3.07
        y: 0.14
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalBasePatrolD: # 基地巡逻点
        x: -3.49
        y: 3.17
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalSlope: # 上坡1
        x: 4.16
        y: -1.46
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalMiddlePatrolA: 
        x: 7.49
        y: 3.36
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalMiddlePatrolB: 
        x: 7.65
        y: 6.48
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalMiddlePatrolC: 
        x: 10.53
        y: 6.06
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalMiddlePatrolD: 
        x: 11.04
        y: 1.15
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalSupply: # 增益点
        x: -1.56
        y: -2.83
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0  
      goalDu: # defend others gongcheng
        x: 2.42
        y: 8.56
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0  
    blue:
      goalNoBullet: # 无子弹点
        x: -4.25
        y: 1.30
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalBasePatrolA: # 基地巡逻点
        x: 4.56
        y: -1.35
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalBasePatrolB: # 基地巡逻点
        x: 3.86
        y: -1.58
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalBasePatrolC: # 基地巡逻点
        x: -3.40
        y: 0.89
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalBasePatrolD: # 基地巡逻点
        x: -2.95
        y: 3.91
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalSlope: # 上坡1
        x: 2.92
        y: -3.39
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalMiddlePatrolA: 
        x: 7.31
        y: 0.81
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalMiddlePatrolB: 
        x: 8.92
        y: 2.28
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalMiddlePatrolC: 
        x: 11.21
        y: -2.05
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalMiddlePatrolD: 
        x: 9.35
        y: -3.02
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0
      goalSupply: # 增益点
        x: -2.94
        y: -2.74
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0 
      goalDu: # defend others gongcheng
        x: -1.56
        y: -2.83
        z: 0.0
        x1: 0.0
        y1: 0.0
        z1: 0.0
        w1: 1.0 